// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irobcjfwpxdlfqtdmxfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyb2JjamZ3cHhkbGZxdGRteGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTQ3NzgsImV4cCI6MjA3MDAzMDc3OH0.d94_jbSPht0STaKoEoaZIdD6Kh_awH41B398tstjpww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});